name: Release on main

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Environment setup
        run: pip install numpy


      - name: Run tests
        run: python test.py

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          TAG=$(git tag --sort=-v:refname | head -n 1)
          if [ -z "$TAG" ]; then
            TAG="v1.0.0"
          else
            BASE=${TAG#v}
            MAJOR=$(echo $BASE | cut -d. -f1)
            MINOR=$(echo $BASE | cut -d. -f2)
            PATCH=$(echo $BASE | cut -d. -f3)
            PATCH=$((PATCH+1))
            TAG="v$MAJOR.$MINOR.$PATCH"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: Release ${{ steps.get_tag.outputs.tag }}
          draft: false
          prerelease: false
